spring:
  datasource:
    url: jdbc:mysql://data.dianpoint.com:3306/circledot?autoReconnect=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: circledot
    password: circledot
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: circledot
  thymeleaf:
    check-template-location: false
    cache: false
  devtools: #热部署生效
    livereload:
      enabled: true
logging:
  level:
    cc.ccoder.circledot: debug