spring:
  datasource:
    url: jdbc:mysql://localhost:3306/circledot?autoReconnect=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: chencong
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: circledot
  thymeleaf:
    check-template-location: false

