spring:
  datasource:
    url: jdbc:mysql://localhost:3306/circledot?useSSL=false
    username: chencong
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: circledot
  thymeleaf:
    check-template-location: false
logging:
  level:
    cc.ccoder.circledot: debug
